# Dependencies
markdown:         kramdown
toc_levels:       1,2
highlighter:      rouge

# Setup
title:            "tagtog"
tagline:          'The Text Annotation Tool to Train AI'
description:      'Official documentation for <a href="https://tagtog.net">tagtog</a>'
app_url:          https://www.tagtog.net
url:              https://docs.tagtog.net
baseurl:
baseurl:
sidebar_toc:
  - name: What's new
    pages:
      - updates

  - name: Tutorials
    pages:
      - quick_tutorials
      - ml
      - train-your-own-models

  - name: Web Application
    pages:
      - projects
      - project_documents
      - webeditor
      - metrics
      - collaboration
      - pdfann

  - name: API
    pages:
      - api_documents_v1
      - api_settings_v1
      - api-projects-v1
      - api_metrics_v0

  - name: Concept Search
    pages:
      - search
      - search_queries

  - name: Formats
    pages:
      - formats
      - anndoc
      - dictionaries

  - name: OnPremises
    pages:
      - on_premises_readme
      - sysadmin-onpremises


author:
  name:           'tagtog Sp. z o.o.'
  url:            https://twitter.com/tagtog_net

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-toc
  - jemoji

# Custom vars
version: 3.2021-W37.0-SNAPSHOT.43
sidebar_home_link: true
search_page: false
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/tagtog/

defaults:
- scope:
    path: "assets/img"
  values:
    image: true

# source: site
